server.port=${PORT:8080}
spring.application.name=educacao-online-api
spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:testdb}
spring.datasource.username=${DATABASE_USERNAME:sa}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
spring.jackson.serialization.write-dates-as-timestamps=false
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
jwt.secret=a75796dca648089b5c60e2c99042290d0f97e1748e924087d033a4af10d82670
